### ISSUE TITLE
Missing condition propertie

### ISSUE THREAD

**Issue by superdaminou** [jtama/chart-to-asciidoc#2]
Release: `0.1.0`

Command: 
```
.\helm-to-asciidoc.exe -c Chart.yaml -v  values.yaml -o test.adoc
```

Output 
```
java.lang.IllegalStateException: Missing required properties: condition
        at org.acme.Dependency$Builder.build(Dependency.java:66)
        at org.acme.Launcher.mapToDependency(Launcher.java:176)
        at java.base@22.0.2/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
        at java.base@22.0.2/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
        at java.base@22.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
        at java.base@22.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
        at java.base@22.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:622)
        at java.base@22.0.2/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
        at java.base@22.0.2/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:631)
        at java.base@22.0.2/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:637)
        at java.base@22.0.2/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:642)
        at org.acme.Launcher.readDependencies(Launcher.java:157)
        at org.acme.Launcher.lambda$mapToChart$3(Launcher.java:144)
        at java.base@22.0.2/java.util.ArrayList.forEach(ArrayList.java:1597)
        at org.acme.Launcher.mapToChart(Launcher.java:135)
        at org.acme.Launcher.readChart(Launcher.java:127)
        at org.acme.Launcher.run(Launcher.java:51)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base@22.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**Comment by jtama** [comment]
When a dependency exists but has no condition, it will fail.

Would it be enough if a null condition is represented by "N/A" ? 

if so, this should be done at the record compact constructor level : `condition = Objects.requireNonNullElse(condition, "N/A")`

@superdaminou would you like to provide a PR ?

**Comment by superdaminou** [comment]
@jtama  here is the PR: https://github.com/jtama/chart-to-asciidoc/pull/3
Feel free to amend if needed. I thought it would be good to add unit test for this kind a case, it's a minimal test implementation for proposal
